#!/bin/bash

##############################################################################
##  Gripes start up script for UN*X
##############################################################################

APP_NAME="Gripes"
APP_BASE_NAME=`basename "$0"`

warn ( ) {
    echo "$*"
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

GRADLE_CMD=""

for ARG in "$@"
do
	if [[ $ARG =~ = ]];
	then 
		GRADLE_CMD="$GRADLE_CMD -P$ARG"
	else
		GRADLE_CMD="$GRADLE_CMD $ARG"
	fi
done
echo $GRADLE_CMD
exec "./gradlew" $GRADLE_CMD