#!/bin/bash

##############################################################################
##  Gripes start up script for UN*X
##############################################################################

APP_NAME="Gripes"
APP_BASE_NAME=`basename "$0"`

warn ( ) {
    echo "$*"
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

GRADLE_CMD=""

if [ "$1" = "create" ]
then
	GRADLE_CMD="-P$2"
else
	GRADLE_CMD=""
fi

exec "./gradlew" $1 $GRADLE_CMD